name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install browsers and drivers
      run: |
        sudo apt update
        sudo apt install -y wget curl unzip xvfb
        wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.34.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.34.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        wget https://ftp.mozilla.org/pub/firefox/releases/127.0/linux-x86_64/en-US/firefox-127.0.tar.bz2
        tar xjf firefox-127.0.tar.bz2
        sudo mv firefox /opt/
        sudo ln -s /opt/firefox/firefox /usr/bin/firefox

    - name: Run tests with pytest headlessly
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 &
        pytest --maxfail=1 --disable-warnings
